/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ProxyControllerInterface extends ethers.utils.Interface {
  functions: {
    "changeAllProxyAdmins(address)": FunctionFragment;
    "changeProxyAdmin(uint256,address)": FunctionFragment;
    "eligManagerImpl()": FunctionFragment;
    "feeDistribImpl()": FunctionFragment;
    "fetchImplAddress(uint256)": FunctionFragment;
    "getAdmin(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "stakingImpl()": FunctionFragment;
    "stakingProviderImpl()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "upgradeProxyTo(uint256,address)": FunctionFragment;
    "vaultFactoryImpl()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "changeAllProxyAdmins",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeProxyAdmin",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "eligManagerImpl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeDistribImpl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fetchImplAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdmin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakingImpl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakingProviderImpl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeProxyTo",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultFactoryImpl",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "changeAllProxyAdmins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeProxyAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eligManagerImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeDistribImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchImplAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingProviderImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeProxyTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultFactoryImpl",
    data: BytesLike
  ): Result;

  events: {
    "ImplAddressSet(uint256,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "ProxyAdminChanged(uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ImplAddressSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProxyAdminChanged"): EventFragment;
}

export type ImplAddressSetEvent = TypedEvent<
  [BigNumber, string] & { index: BigNumber; impl: string }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type ProxyAdminChangedEvent = TypedEvent<
  [BigNumber, string] & { index: BigNumber; newAdmin: string }
>;

export class ProxyController extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ProxyControllerInterface;

  functions: {
    changeAllProxyAdmins(
      newAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeProxyAdmin(
      index: BigNumberish,
      newAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    eligManagerImpl(overrides?: CallOverrides): Promise<[string]>;

    feeDistribImpl(overrides?: CallOverrides): Promise<[string]>;

    fetchImplAddress(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAdmin(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { admin: string }>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stakingImpl(overrides?: CallOverrides): Promise<[string]>;

    stakingProviderImpl(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeProxyTo(
      index: BigNumberish,
      newImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    vaultFactoryImpl(overrides?: CallOverrides): Promise<[string]>;
  };

  changeAllProxyAdmins(
    newAdmin: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeProxyAdmin(
    index: BigNumberish,
    newAdmin: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  eligManagerImpl(overrides?: CallOverrides): Promise<string>;

  feeDistribImpl(overrides?: CallOverrides): Promise<string>;

  fetchImplAddress(
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAdmin(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stakingImpl(overrides?: CallOverrides): Promise<string>;

  stakingProviderImpl(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeProxyTo(
    index: BigNumberish,
    newImpl: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  vaultFactoryImpl(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    changeAllProxyAdmins(
      newAdmin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    changeProxyAdmin(
      index: BigNumberish,
      newAdmin: string,
      overrides?: CallOverrides
    ): Promise<void>;

    eligManagerImpl(overrides?: CallOverrides): Promise<string>;

    feeDistribImpl(overrides?: CallOverrides): Promise<string>;

    fetchImplAddress(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getAdmin(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    stakingImpl(overrides?: CallOverrides): Promise<string>;

    stakingProviderImpl(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeProxyTo(
      index: BigNumberish,
      newImpl: string,
      overrides?: CallOverrides
    ): Promise<void>;

    vaultFactoryImpl(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ImplAddressSet(uint256,address)"(
      index?: null,
      impl?: null
    ): TypedEventFilter<
      [BigNumber, string],
      { index: BigNumber; impl: string }
    >;

    ImplAddressSet(
      index?: null,
      impl?: null
    ): TypedEventFilter<
      [BigNumber, string],
      { index: BigNumber; impl: string }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "ProxyAdminChanged(uint256,address)"(
      index?: null,
      newAdmin?: null
    ): TypedEventFilter<
      [BigNumber, string],
      { index: BigNumber; newAdmin: string }
    >;

    ProxyAdminChanged(
      index?: null,
      newAdmin?: null
    ): TypedEventFilter<
      [BigNumber, string],
      { index: BigNumber; newAdmin: string }
    >;
  };

  estimateGas: {
    changeAllProxyAdmins(
      newAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeProxyAdmin(
      index: BigNumberish,
      newAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    eligManagerImpl(overrides?: CallOverrides): Promise<BigNumber>;

    feeDistribImpl(overrides?: CallOverrides): Promise<BigNumber>;

    fetchImplAddress(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAdmin(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stakingImpl(overrides?: CallOverrides): Promise<BigNumber>;

    stakingProviderImpl(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeProxyTo(
      index: BigNumberish,
      newImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    vaultFactoryImpl(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    changeAllProxyAdmins(
      newAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeProxyAdmin(
      index: BigNumberish,
      newAdmin: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    eligManagerImpl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeDistribImpl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fetchImplAddress(
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAdmin(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stakingImpl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stakingProviderImpl(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeProxyTo(
      index: BigNumberish,
      newImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    vaultFactoryImpl(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
